# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :tests do
    run_tests(
      scheme: "ChatGPT",
      devices: "iPhone 14 Pro",
      output_directory: "./build/test",
      code_coverage: true,
      clean: true
    )
    coverage_report()
  end

  lane :coverage_report do
    sh "rm -rf .././build/test/coverage"
    xcov(
      scheme: "ChatGPT",
      output_directory: "./build/test/coverage",
      exclude_targets: "MarkdownUI, Alamofire"
    )
  end
end
